name: 'Setup StackQL'

on:
  push:
    branches:
    - main
  pull_request:
jobs:
  stackql-exec-google-example:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    name: 'StackQL exec Google '

    steps: 
    - name: Checkout
      uses: actions/checkout@v3

    - name: Prep Google Creds (Windows)
      if: ${{ matrix.os == 'windows-latest'}}
      run: | ## use the secret to create json file
        $GoogleCreds = [System.Environment]::GetEnvironmentVariable("GOOGLE_CREDS_ENV")
        $GoogleCredsDecoded = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($GoogleCreds))
        Write-Output $GoogleCredsDecoded | Set-Content sa-key.json
      shell: pwsh
      env:
        GOOGLE_CREDS_ENV: ${{ secrets.GOOGLE_CREDS }}
  
    - name: Prep Google Creds (bash)
      if: ${{ matrix.os != 'windows-latest' }}
      shell: bash
      run: | ## use the base64 encoded secret to create json file
        sudo echo ${{ secrets.GOOGLE_CREDS }} | base64 -d > sa-key.json

    - name: exec google example with query file
      id: exec-stackql-file
      uses: ./
      with:
        auth_obj_path: './stackql_scripts/auth.json'
        query_file_path: './stackql_scripts/google-example.iql'

    - name: exec github example with query string
      id: exec-stackql-string
      uses: ./
      with:
        auth_str: '{ "github": { "type": "basic", "credentialsenvvar": "STACKQL_GITHUB_CREDS" } }'
        query: "REGISTRY PULL github v23.01.00104;
                SHOW PROVIDERS;
                select total_private_repos
                from github.orgs.orgs
                where org = 'stackql';"
      env: 
        STACKQL_GITHUB_CREDS: ${{ secrets.STACKQL_GITHUB_CREDS }}

    - name: validate exec-stackql output
      shell: bash
      run: |
        echo "exec-stackql-file output: ${{ steps.exec-stackql-file.outputs.result }}"
        if [ -z ${{ steps.exec-stackql-file.outputs.result }} ]; then
          echo "exec-stackql output does not contain expected result"
          exit 1
        fi
        echo "exec-stackql-string output: ${{ steps.exec-stackql-string.outputs.result }}"
        if [ -z ${{ steps.exec-stackql-string.outputs.result }} ]; then
          echo "exec-stackql output does not contain expected result"
          exit 1
        fi



