name: 'StackQL Exec Test'

on:
  push:
    branches:
    - main
  pull_request:
jobs:
  stackql-exec-google-example:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    name: 'StackQL exec Google '

    steps: 
    - name: Checkout
      uses: actions/checkout@v3

    - name: exec google example with query file
      id: stackql-exec-file
      uses: ./
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDS }}
        query_file_path: './stackql_scripts/google-example.iql'

    - name: exec github example with query string
      id: stackql-exec-string
      uses: ./
      with:
        query: "REGISTRY PULL github v23.01.00104;
                SHOW PROVIDERS;
                select total_private_repos
                from github.orgs.orgs
                where org = 'stackql';"
      env: 
        STACKQL_GITHUB_CREDS: ${{ secrets.STACKQL_GITHUB_CREDS }}

    - name: validate stackql-exec output
      shell: bash
      run: |
        if [ -z '${{ steps.stackql-exec-file.outputs.exec-result }}' ]; then
          echo "exec-stackql output does not contain expected result"
          exit 1
        fi
        if [ -z '${{ steps.stackql-exec-string.outputs.exec-result }}' ]; then
          echo "exec-stackql output does not contain expected result"
          exit 1
        fi


